# Don't edit this file
#
# It was auto generated by cmake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES mod_napmath mod_napscene mod_napaudio)
set(DEEP_DEPENDENT_NAP_MODULES mod_napmath mod_napscene mod_napaudio)
