// Don't edit this file. It is generated by cmake.

#pragma once

#include "pluginterfaces/base/fplatform.h"
#include "pluginterfaces/base/funknown.h"
#include "pluginterfaces/vst/vstspeaker.h"

#define stringPluginName		"fmsynthplugin"
#define stringPluginVersion     "0.0.1"

#if SMTG_PLATFORM_64
#define stringFileDescription	stringPluginName" VST3-SDK (64Bit)"
#else
#define stringFileDescription	stringPluginName" VST3-SDK"
#endif

#define stringCompanyName		"NAP Framework"
#define stringCompanyWeb		"https://github.com/napframework/nap"
#define stringCompanyEmail		""

#define stringAppStructurePath	"data/objects.json"
#define stringPluginClass		"nap::FMSynthPlugin"
#define stringPluginCategory	"Instrument|Synth"

static const Steinberg::FUID pluginFUID (0xBD58B550, 0xF9E5634E, 0x9D2EFF39, 0xEA0927B3);
static const Steinberg::Vst::SpeakerArrangement pluginAudioInput = Steinberg::Vst::SpeakerArr::kEmpty;
static const Steinberg::Vst::SpeakerArrangement pluginAudioOutput = Steinberg::Vst::SpeakerArr::kStereo;
